### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'speakerX')

### ISSUE THREAD

**Issue by yslion** [pixiv/ChatVRM#15]
![image](https://github.com/pixiv/ChatVRM/assets/4454836/594f0c74-5c55-4d91-a70b-f97b0fa0b2a2)

![image](https://github.com/pixiv/ChatVRM/assets/4454836/6b302afc-b94d-4e64-abc4-a819ae9fa55e)

**Comment by 0b5vr** [comment]
ChatVRM is intended to share technology and provide demonstrations, and this repository has not been actively operated.
Considering our maintenance system, we will archive this repository with the current code.
If you would like to change ChatVRM in the future, we would appreciate it if you fork it.
We apologize for the late response to your kind contributions.
