### ISSUE TITLE
Demo not working - maybe due to deprecated model? 

### ISSUE THREAD

**Issue by nucleiis** [pixiv/ChatVRM#21]
I saw there's the same issue which was closed while ago. But it seems it still not returning any response. I have like 30 USD balance in my openai account and I am actively invoking various gpt models like gpt4-0125-preview.

Maybe it's due to deprecated model such as gpt3-turbo 0630 something like that, I had the same issue with my own program while ago and I had to change my gpt3.5 model.

Hope it gets fixed!

**Comment by 0b5vr** [comment]
ChatVRM is intended to share technology and provide demonstrations, and this repository has not been actively operated.
Considering our maintenance system, we will archive this repository with the current code.
If you would like to change ChatVRM in the future, we would appreciate it if you fork it.
We apologize for the late response to your kind contributions.
