### ISSUE TITLE
English / Arabic version 👯 

### ISSUE THREAD

**Issue by maljefairi** [pixiv/ChatVRM#6]
thanks for this great job, i would love to have arabic/english version

**Comment by devout1337** [comment]
translate it yourself lazy. 😝  i did, it only takes like 30 mins-1 hour. probably even less if u didnt do it manually like my dumbass. 

also, here's a pull request that added the translation: https://github.com/pixiv/ChatVRM/pull/4

**Comment by 0b5vr** [comment]
ChatVRM is intended to share technology and provide demonstrations, and this repository has not been actively operated.
Considering our maintenance system, we will archive this repository with the current code.
If you would like to change ChatVRM in the future, we would appreciate it if you fork it.
We apologize for the late response to your kind contributions.
